spring:
  application:
    name: notification-service  # Nombre del microservicio
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5433}/brightmind  # URL de la base de datos
    username: ${DB_USERNAME:root}                 # Usuario de la base de datos
    password: ${DB_PASSWORD:root}                # Contraseña de la base de datos (la que estás usando en pgAdmin)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update                                # O "create" si estás en desarrollo
    show-sql: true                                    # Muestra las consultas SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}  # URL del servidor Eureka
  instance:
    prefer-ip-address: true
    hostname: ${APP_HOSTNAME:localhost}  # Asegúrate de que esto sea correcto si usas localhost
    non-secure-port: 8086  # Este es el puerto que debería usar Eureka para acceder al servicio

server:
  port: 8086  # Puedes usar un puerto diferente para cada microservicio
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs  # Ruta por defecto de Swagger para los endpoints de OpenAPI
  swagger-ui:
    path: /swagger-ui.html  # Ruta del UI de Swagger

